name: Mert Skor - Mac Guncelleme Cron

on:
  schedule:
    # 2 saatte bir çalışır (Örn: 10:00, 12:00, 14:00...)
    - cron: '0 */2 * * *'
    
  workflow_dispatch: # Manuel çalıştırmak istersen buton hala orada

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Vercel API Tetikle
        run: |
          curl -X GET "https://soccer2-ashen.vercel.app/api/fetch-matches" \
          -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}"
